"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { Cpu, Download, Info, AlertTriangle, CheckCircle, XCircle, Search, Table as TableIcon } from "lucide-react"
import { PageHeader } from "@/components/page-header"
import { InfoCard } from "@/components/info-card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

const installSteps = [
  { step: "Steam'i Yapılandır", detail: "Görev Yöneticisi > Başlangıç sekmesinden Steam'i Devre Dışı bırakın ve Steam'i tamamen kapatın." },
  { step: "Dosyayı Yerleştir", detail: "Win + R tuşlarına basıp shell:startup yazın. İndirdiğiniz dosyayı açılan klasöre atın." },
  { step: "Sonuç", detail: "Bilgisayar her açıldığında Steam otomatik olarak en verimli çekirdeklerde çalışmaya başlar." },
]

const removeSteps = [
  { step: "Win + R ile shell:startup klasörüne gidin ve .bat dosyasını silin." },
  { step: "Görev Yöneticisi > Başlangıç sekmesinden Steam'i tekrar Etkin hale getirin." },
  { step: "Bilgisayarı yeniden başlatın; her şey varsayılana dönecektir." },
]

function generateBatContent(cores: number, threads: number): string {
  let mask = BigInt(0)
  for (let i = 2; i < threads; i++) {
    mask |= BigInt(1) << BigInt(i)
  }
  const hexMask = "0x" + mask.toString(16).toUpperCase()
  
  return `@echo off
:: CS2 and Rust CPU 0 Isolation Script
:: Generated by CStweak.com.tr

:: Wait for system to fully boot
timeout /t 10 /nobreak >nul

:: Start Steam with affinity excluding CPU 0 & 1
start "" /affinity ${hexMask} "C:\\Program Files (x86)\\Steam\\Steam.exe"

echo Steam started with affinity mask ${hexMask}
echo CPU cores used: 2-${threads - 1} (excluding CPU 0 & 1)
`
}

export default function CPU0Page() {
  const [cores, setCores] = useState("")
  const [threads, setThreads] = useState("")

  const handleDownload = () => {
    const coreCount = parseInt(cores) || 8
    const threadCount = parseInt(threads) || 16
    
    const content = generateBatContent(coreCount, threadCount)
    const blob = new Blob([content], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "cpu0_isolation_cstweak.bat"
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8 pb-20">
      <PageHeader
        icon={Cpu}
        title="CPU0 İzolasyonu"
        description="CS2 ve Rust için İlk Fiziksel Çekirdek (CPU 0 & 1) İzolasyonu"
      />

      <div className="grid gap-6 mb-12">
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
          <InfoCard icon={AlertTriangle} title="Önemli Not" variant="warning">
            <p>
              {"Bu optimizasyon, Steam ve oyunların sistem kaynaklarını daha verimli kullanmasını sağlar. İlk fiziksel çekirdek (CPU 0 & 1) sistem işlemleri için ayrılırken, oyunlar diğer çekirdeklerde çalışır. Çekirdek sayılarınızı doğru girmeniz kritiktir."}
            </p>
          </InfoCard>
        </motion.div>

        {/* Yeni: İnsanlar çekirdek sayısını nasıl bulacak? Bölümü */}
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <InfoCard icon={Search} title="Değerleri Nasıl Bulurum?" variant="info">
            <div className="text-sm space-y-2">
              <p>İşlemci bilgilerinize saniyeler içinde bakabilirsiniz:</p>
              <ol className="list-decimal pl-5 space-y-1">
                <li><kbd className="px-1 py-0.5 rounded bg-secondary border border-border">Ctrl + Shift + Esc</kbd> tuşlarına basarak Görev Yöneticisi'ni açın.</li>
                <li>Üstteki <strong>Performans</strong> sekmesine ve ardından <strong>İşlemci (CPU)</strong> seçeneğine tıklayın.</li>
                <li>Sağ altta yazan <strong>Çekirdekler</strong> ve <strong>Mantıksal İşlemciler</strong> değerlerini aşağıdaki kutucuklara girin.</li>
              </ol>
            </div>
          </InfoCard>
        </motion.div>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="mb-12 rounded-lg border border-primary/30 bg-primary/5 p-6"
      >
        <h2 className="text-xl font-semibold mb-6 flex items-center gap-2">
          <Cpu className="h-5 w-5 text-primary" />
          Optimizer .BAT Oluştur ve İndir
        </h2>
        
        <div className="grid gap-4 sm:grid-cols-2 mb-6">
          <div className="space-y-2">
            <Label htmlFor="cores">Çekirdek Sayısı (Cores)</Label>
            <Input
              id="cores"
              type="number"
              placeholder="Örn: 8"
              value={cores}
              onChange={(e) => setCores(e.target.value)}
              className="bg-background"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="threads">Mantıksal İşlemci (Threads)</Label>
            <Input
              id="threads"
              type="number"
              placeholder="Örn: 16"
              value={threads}
              onChange={(e) => setThreads(e.target.value)}
              className="bg-background"
            />
          </div>
        </div>

        <Button onClick={handleDownload} className="w-full sm:w-auto font-bold uppercase tracking-widest text-[11px] h-12">
          <Download className="h-4 w-4 mr-2" />
          Optimizer .BAT Oluştur ve İndir
        </Button>

        {/* Hızlı Referans Tablosu */}
        <div className="mt-8 pt-6 border-t border-border/50">
          <div className="flex items-center gap-2 text-xs font-bold text-muted-foreground uppercase mb-3 tracking-widest">
            <TableIcon className="h-3 w-3" /> Popüler İşlemci Rehberi
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {[
              { cpu: "R5 5600 / i5-12400", core: "6", thread: "12" },
              { cpu: "R7 5700X / i7-10700K", core: "8", thread: "16" },
              { cpu: "R9 5900X / i9-12900K", core: "12/16", thread: "24/32" },
            ].map((item, i) => (
              <div key={i} className="text-[11px] p-2 rounded border border-border bg-background/50">
                <div className="font-bold text-primary truncate">{item.cpu}</div>
                <div className="text-muted-foreground">{item.core} Çekirdek / {item.thread} Thread</div>
              </div>
            ))}
          </div>
        </div>
      </motion.div>

      <section className="mb-12">
        <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
          <CheckCircle className="h-5 w-5 text-green-500" />
          Kurulum Talimatları
        </h2>
        <div className="space-y-3">
          {installSteps.map((item, index) => (
            <motion.div
              key={index}
              className="flex items-start gap-3 rounded-lg border border-border bg-card p-4"
            >
              <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-green-500/10 text-xs font-medium text-green-500">
                {index + 1}
              </span>
              <div>
                <span className="font-medium text-sm sm:text-base">{item.step}</span>
                <p className="text-sm text-muted-foreground mt-1 leading-relaxed">{item.detail}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
          <XCircle className="h-5 w-5 text-red-500" />
          Ayarları Geri Al (Kaldırma)
        </h2>
        <div className="space-y-2">
          {removeSteps.map((item, index) => (
            <motion.div
              key={index}
              className="flex items-start gap-3 rounded-lg border border-red-500/30 bg-red-500/5 p-3"
            >
              <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-red-500/10 text-xs font-medium text-red-500">
                {index + 1}
              </span>
              <span className="text-sm text-muted-foreground">{item.step}</span>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  )
}